export enum FoodType {
  DAIRY_FREE_ALTERNATIVES = 'Dairy-Free Alternatives',
  DRIED_BEANS = 'Dried Beans',
  FROZEN_MEALS = 'Frozen Meals',
  GLUTEN_FREE_BAKING_PANCAKE_MIXES = 'Gluten-Free Baking/Pancake Mixes',
  GLUTEN_FREE_BREAD = 'Gluten-Free Bread',
  GLUTEN_FREE_PASTA = 'Gluten-Free Pasta',
  GLUTEN_FREE_TORTILLAS_FROZEN = 'Gluten-Free Tortillas (Frozen)',
  GRANOLA = 'Granola',
  GRANOLA_BARS = 'Granola Bars',
  MASA_HARINA_FLOUR = 'Masa Harina Flour',
  NON_GMO_COOKIES = 'Non-GMO Cookies',
  OLIVE_OIL = 'Olive Oil',
  QUINOA = 'Quinoa',
  RICE_CERTIFIED_GLUTEN_FREE = 'Rice (Certified Gluten Free)',
  SPREADS_SEED_BUTTERS = 'Spreads/Seed Butters (Peanut Butter Alternative)',
  SNACKS = 'Snacks',
  TEFF_FLOUR = 'Teff Flour',
}
