export enum Role {
  ADMIN = 'ADMIN',
  VOLUNTEER = 'VOLUNTEER',
  LEAD_VOLUNTEER = 'LEAD_VOLUNTEER',
  STANDARD_VOLUNTEER = 'STANDARD_VOLUNTEER',
  NON_PANTRY_VOLUNTEER = 'NON_PANTRY_VOLUNTEER',
  PANTRY = 'PANTRY',
  FOODMANUFACTURER = 'FOODMANUFACTURER',
}
